# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: SetUp NodeJs
      uses: actions/setup-node@v3
      with:
        node-version: 16.3.0
        cache: 'npm'
        NODE_OPTIONS: "--max_old_space_size=8192"

    - run: npm install
    - run: npm run wdio
    - run: npm run report

    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: allure reports
        path: allure-report
